[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:redis]
command=redis-server --save "" --appendonly no
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:api]
command=uvicorn app.main:app --host 0.0.0.0 --port %(ENV_PORT)s
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:worker]
command=arq app.worker.worker.WorkerSettings
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
